/* UNIDADES DE MEDIDA SUNAT */

DELETE FROM unidades_medida;

INSERT INTO unidades_medida (codigo, descripcion, simbolo) VALUES 
('ZZ', 'Servicio', 'SERV'),
('BX', 'Caja', 'CAJ'),
('GLL', 'Galon', 'GL'),
('GRM', 'Gramos', 'GR'),
('KGM', 'Kilos', 'KG'),
('LTR', 'Litro', 'LT'),
('MTR', 'Metro', 'M'),
('FOT', 'Pies', 'PIE'),
('INH', 'Pulgadas', 'INCH'),
('NIU', 'Unidad', 'UND'),
('YRD', 'Yarda', 'YD'),
('HUR', 'Hora', 'HR'),
('TNE', 'Toneladas', 'TNL'),
('DZN', 'Docena', 'DOC'),
('QD', 'Cuarto de docena', '1/4 DOC'),
('PK', 'Paquete', 'PQT'),
('MTQ', 'Metro cúbico', 'M3'),
('HD', 'Media docena', '1/2 DOC'),
('PR', 'Par', 'PAR'),
('JG', 'Jarra', 'JARR'),
('JR', 'Frasco', 'FCO'),
('KT', 'Kit', 'KIT'),
('CH', 'Envase', 'ENV'),
('AV', 'Capsula', 'CAPS'),
('CT', 'Carton', 'CTON'),
('CY', 'Cilindro', 'CIL'),
('BE', 'Fardo', 'FARD'),
('BG', 'Bolsa', 'BOLS'),
('BJ', 'Balde', 'BALD'),
('SET', 'Juego', 'JGO'),
('BLL', 'Barril', 'BRL'),
('RM', 'Resma', 'RESM'),
('BO', 'Botellas', 'BOT'),
('SA', 'Saco', 'SCO'),
('BT', 'Tornillo', 'TORN'),
('C62', 'Piezas', 'PZ'),
('U2', 'Tableta o blister', 'BLIST'),
('CA', 'Latas', 'LT'),
('CEN', 'Centenar o ciento', 'CTO'),
('CMT', 'Centimetro', 'CM'),
('CMK', 'Centimetro cuadrado', 'CM3'),
('CMQ', 'Centimetro cubico', 'CM2'),
('DZP', 'Docena de paquetes', 'DOC2'),
('FTK', 'Pies cuadrados', 'PIE2'),
('FTQ', 'Pies cubicos', 'PIE3'),
('GLI', 'Galon ingles', 'GL'),
('HT', 'Media hora', '1/2 H'),
('KTM', 'Kilometro', 'KM'),
('KWH', 'Kilovatio hora', 'KWxH'),
('MWH', 'Megavatio hora', 'MWxH'),
('LBR', 'Libras', 'LB'),
('LEF', 'Hoja', 'HOJA'),
('MGM', 'Miligramos', 'MG'),
('MIL', 'Millar', 'MIL'),
('MLT', 'Mililitro', 'ML'),
('MMT', 'Milimetro', 'ML'),
('MMK', 'Milimetro cuadrado', 'ML2'),
('MMQ', 'Milimetro cubico', 'ML3'),
('MTK', 'Metro cuadrado', 'M2'),
('ONZ', 'Onzas', 'ONZ'),
('PF', 'Paletas', 'PAL'),
('PG', 'Placas', 'PLAC'),
('RD', 'Varilla', 'VAR'),
('RL', 'Carrete', 'CRR'),
('SEC', 'Segundo', 'SEG'),
('ST', 'Pliego', 'PLGO'),
('TU', 'Tubos', 'TB'),
('UM', 'Millon', 'MILL'),
('MU', 'Millon de unidades', null),
('P6', 'Six Pack', null)
